service: wxtj-converter-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  httpApi:
    cors: true
  environment:
    SPOTIFY_API_CLIENT_ID: ${env:SPOTIFY_API_CLIENT_ID}
    SPOTIFY_API_CLIENT_SECRET: ${env:SPOTIFY_API_CLIENT_SECRET}

functions:
  convert_new_playlist:
    handler: handler.convert_new_playlist
    events:
      - httpApi:
          path: /convert_new_playlist
          method: post
  convert_old_playlist:
    handler: handler.convert_old_playlist
    events:
      - httpApi:
          path: /convert_old_playlist
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux  