service: wxtj-converter-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  convert_new_playlist:
    handler: handler.convert_new_playlist
    events:
      - httpApi:
          path: /convert_new_playlist
          method: post
  convert_old_playlist:
    handler: handler.convert_old_playlist
    events:
      - httpApi:
          path: /convert_old_playlist
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux  